import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/templates/Layout/Layout'

const Home: NextPage = () => {
  return (
    <Layout>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>Sorteo App</h1>
      </div>
    </Layout>
  )
}

export default Home
